blank_issues_enabled: false
contact_links:
  - name: Ask a question about Shrine
    url: https://github.com/shrinerb/shrine/discussions/new
    about: Ask a question or request support for Shrine. If you're unsure it's a bug, please ask here first!
