name: Report a bug 🐛
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Self-help

        Before you make a bug report, please check our existing resources to see if it has already been discussed/reported:
        - [Reported bugs](https://github.com/shrinerb/shrine/issues)
        - [GitHub Discussions](https://github.com/shrinerb/shrine/discussions/)
        - [Shrine Discourse (A Question / Answer Forum)](https://discourse.shrinerb.com/)        

  - type: textarea
    attributes:
      label: Report
      description: "What bug have you encountered?"
      placeholder: "A clear and concise description of what the bug is."
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: Also tell us, what did you see is happen?
      placeholder: Tell us what you see that is happening
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Reproducing The Bug
        This is critical to enable a quick fix!

        Provide a self-contained example code
        ([Sequel/ActiveRecord templates](https://github.com/shrinerb/shrine/blob/master/CONTRIBUTING.md))
        to show the problem, and the full backtrace of any exception.
        Or to make it even easier: simply clone this repository to demonstrate
        through a code sample: https://github.com/benkoshy/debugging-shrine-example
  - type: textarea
    attributes:
      label: Steps to Reproduce the Problem
      description: How can we reproduce this bug? This is critical to enable a quick fix!
      value: |
        1.
        2. Ruby code to demonstrate the problem.
    validations:
      required: true

  - type: input
    attributes:
      label: Ruby Version
      description: What version of Ruby are you using?
      placeholder: e.g. ruby 3.0.1p64
    validations:
      required: false

  - type: input
    attributes:
      label: Shrine Version
      description: What version of the shrine gem are you using?
      placeholder: e.g. 3.4.0
    validations:
      required: false

  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: "Let us know if you have anything else to share"
