source "https://rubygems.org"

# Web framework
gem "puma"
gem "roda", "~> 3.9"

# Rendering
gem "tilt", ">= 2.0.8"
gem "erubi"
gem "forme", "~> 1.8"

# Database
gem "sequel"
gem "sqlite3"

# Attachments
gem "shrine", path: ".."
gem "aws-sdk-s3", "~> 1.14"
gem "dotenv"
gem "image_processing", "~> 1.0"
gem "marcel"
gem "dry-monitor"

# Background jobs
gem "sucker_punch", "~> 2.0"

# Debugging
gem "pry-byebug"

# Testing
gem "minitest"
gem "capybara"
gem "chromedriver-helper"
gem "selenium-webdriver"
gem "rake"
